---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-iaas
  labels:
    app: mysite-iaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-iaas
  template:
    metadata:
      labels:
        app: mysite-iaas
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: mysite-iaas-html
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-iaas-service
spec:
  selector:
    app: mysite-iaas
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mysite-iaas-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`ip.regnumtuum.com`) && PathPrefix(`/iaas`)
    kind: Rule
    services:
    - name: mysite-iaas-service
      port: 80
    middlewares:
      - name: mysite-iaas-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mysite-iaas-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /iaas
